/*
 * handler.c
 * Unified event handler dispatch system
 * Author: Michael Czigler
 * License: MIT
 */

#include "handler.h"

/* Unified handler table combining protocol and CTCP handlers */
static const struct handler_entry_table handler_table[] = {
    /* CTCP handlers - processed first for CTCP events */
    { EVENT_CTCP_CLIENTINFO,           ctcp_handle_clientinfo },
    { EVENT_CTCP_PING,                 ctcp_handle_ping },
    { EVENT_CTCP_TIME,                 ctcp_handle_time },
    { EVENT_CTCP_VERSION,              ctcp_handle_version },
    
    /* Protocol display handlers */
    { EVENT_CTCP_ACTION,               protocol_ctcp_action },
    { EVENT_CTCP_DCC,                  protocol_ctcp_info },
    
    /* Core IRC protocol handlers */
    { EVENT_EXT_AUTHENTICATE,          protocol_authenticate },
    { EVENT_JOIN,                      protocol_noop },
    { EVENT_PART,                      protocol_noop },
    { EVENT_PING,                      protocol_ping },
    { EVENT_QUIT,                      protocol_noop },
    { EVENT_PRIVMSG,                   protocol_privmsg },
    { EVENT_NICK,                      protocol_nick },
    { EVENT_NOTICE,                    protocol_notice },
    { EVENT_KICK,                      protocol_info },
    { EVENT_EXT_CAP,                   protocol_info },
    { EVENT_MODE,                      protocol_info },
    { EVENT_TOPIC,                     protocol_info },
    
    /* Numeric replies */
    { EVENT_001_RPL_WELCOME,           protocol_welcome },
    { EVENT_002_RPL_YOURHOST,          protocol_info },
    { EVENT_003_RPL_CREATED,           protocol_info },
    { EVENT_004_RPL_MYINFO,            protocol_info },
    { EVENT_005_RPL_BOUNCE,            protocol_info },
    { EVENT_042_RPL_YOURID,            protocol_info },
    { EVENT_200_RPL_TRACELINK,         protocol_info },
    { EVENT_201_RPL_TRACECONNECTING,   protocol_info },
    { EVENT_202_RPL_TRACEHANDSHAKE,    protocol_info },
    { EVENT_203_RPL_TRACEUNKNOWN,      protocol_info },
    { EVENT_204_RPL_TRACEOPERATOR,     protocol_info },
    { EVENT_205_RPL_TRACEUSER,         protocol_info },
    { EVENT_206_RPL_TRACESERVER,       protocol_info },
    { EVENT_207_RPL_TRACESERVICE,      protocol_info },
    { EVENT_208_RPL_TRACENEWTYPE,      protocol_info },
    { EVENT_209_RPL_TRACECLASS,        protocol_info },
    { EVENT_211_RPL_STATSLINKINFO,     protocol_info },
    { EVENT_212_RPL_STATSCOMMANDS,     protocol_info },
    { EVENT_213_RPL_STATSCLINE,        protocol_info },
    { EVENT_215_RPL_STATSILINE,        protocol_info },
    { EVENT_216_RPL_STATSKLINE,        protocol_info },
    { EVENT_218_RPL_STATSYLINE,        protocol_info },
    { EVENT_219_RPL_ENDOFSTATS,        protocol_info },
    { EVENT_221_RPL_UMODEIS,           protocol_info },
    { EVENT_234_RPL_SERVLIST,          protocol_info },
    { EVENT_235_RPL_SERVLISTEND,       protocol_info },
    { EVENT_241_RPL_STATSLLINE,        protocol_info },
    { EVENT_242_RPL_STATSUPTIME,       protocol_info },
    { EVENT_243_RPL_STATSOLINE,        protocol_info },
    { EVENT_244_RPL_STATSHLINE,        protocol_info },
    { EVENT_245_RPL_STATSSLINE,        protocol_info },
    { EVENT_250_RPL_STATSCONN,         protocol_info },
    { EVENT_251_RPL_LUSERCLIENT,       protocol_info },
    { EVENT_252_RPL_LUSEROP,           protocol_info },
    { EVENT_253_RPL_LUSERUNKNOWN,      protocol_info },
    { EVENT_254_RPL_LUSERCHANNELS,     protocol_info },
    { EVENT_255_RPL_LUSERME,           protocol_info },
    { EVENT_256_RPL_ADMINME,           protocol_info },
    { EVENT_257_RPL_ADMINLOC1,         protocol_info },
    { EVENT_258_RPL_ADMINLOC2,         protocol_info },
    { EVENT_259_RPL_ADMINEMAIL,        protocol_info },
    { EVENT_261_RPL_TRACELOG,          protocol_info },
    { EVENT_263_RPL_TRYAGAIN,          protocol_info },
    { EVENT_265_RPL_LOCALUSERS,        protocol_info },
    { EVENT_266_RPL_GLOBALUSERS,       protocol_info },
    { EVENT_300_RPL_NONE,              protocol_info },
    { EVENT_301_RPL_AWAY,              protocol_info },
    { EVENT_302_RPL_USERHOST,          protocol_info },
    { EVENT_303_RPL_ISON,              protocol_info },
    { EVENT_305_RPL_UNAWAY,            protocol_info },
    { EVENT_306_RPL_NOWAWAY,           protocol_info },
    { EVENT_311_RPL_WHOISUSER,         protocol_info },
    { EVENT_312_RPL_WHOISSERVER,       protocol_info },
    { EVENT_313_RPL_WHOISOPERATOR,     protocol_info },
    { EVENT_314_RPL_WHOWASUSER,        protocol_info },
    { EVENT_315_RPL_ENDOFWHO,          protocol_info },
    { EVENT_317_RPL_WHOISIDLE,         protocol_info },
    { EVENT_318_RPL_ENDOFWHOIS,        protocol_info },
    { EVENT_319_RPL_WHOISCHANNELS,     protocol_info },
    { EVENT_322_RPL_LIST,              protocol_info },
    { EVENT_323_RPL_LISTEND,           protocol_info },
    { EVENT_324_RPL_CHANNELMODEIS,     protocol_info },
    { EVENT_328_RPL_CHANNEL_URL,       protocol_info },
    { EVENT_331_RPL_NOTOPIC,           protocol_info },
    { EVENT_332_RPL_TOPIC,             protocol_info },
    { EVENT_333_RPL_TOPICWHOTIME,      protocol_info },
    { EVENT_341_RPL_INVITING,          protocol_info },
    { EVENT_346_RPL_INVITELIST,        protocol_info },
    { EVENT_347_RPL_ENDOFINVITELIST,   protocol_info },
    { EVENT_348_RPL_EXCEPTLIST,        protocol_info },
    { EVENT_349_RPL_ENDOFEXCEPTLIST,   protocol_info }, 
    { EVENT_351_RPL_VERSION,           protocol_info },
    { EVENT_352_RPL_WHOREPLY,          protocol_info },
    { EVENT_353_RPL_NAMREPLY,          protocol_info },
    { EVENT_364_RPL_LINKS,             protocol_info },
    { EVENT_365_RPL_ENDOFLINKS,        protocol_info },
    { EVENT_366_RPL_ENDOFNAMES,        protocol_info },
    { EVENT_367_RPL_BANLIST,           protocol_info },
    { EVENT_368_RPL_ENDOFBANLIST,      protocol_info },
    { EVENT_369_RPL_ENDOFWHOWAS,       protocol_info },
    { EVENT_371_RPL_INFO,              protocol_info },
    { EVENT_372_RPL_MOTD,              protocol_info },
    { EVENT_374_RPL_ENDOFINFO,         protocol_info },
    { EVENT_375_RPL_MOTDSTART,         protocol_info },
    { EVENT_376_RPL_ENDOFMOTD,         protocol_info },
    { EVENT_381_RPL_YOUREOPER,         protocol_info },
    { EVENT_382_RPL_REHASHING,         protocol_info },
    { EVENT_383_RPL_YOURESERVICE,      protocol_info },
    { EVENT_391_RPL_TIME,              protocol_info },
    { EVENT_392_RPL_USERSSTART,        protocol_info },
    { EVENT_393_RPL_USERS,             protocol_info },
    { EVENT_394_RPL_ENDOFUSERS,        protocol_info },
    { EVENT_395_RPL_NOUSERS,           protocol_info },
    { EVENT_396_RPL_HOSTHIDDEN,        protocol_info },
    { EVENT_704_RPL_HELPSTART,         protocol_info },
    { EVENT_705_RPL_HELPTXT,           protocol_info },
    { EVENT_706_RPL_ENDOFHELP,         protocol_info },
    { EVENT_900_RPL_LOGGEDIN,          protocol_info },
    { EVENT_901_RPL_LOGGEDOUT,         protocol_info },
    { EVENT_903_RPL_SASLSUCCESS,       protocol_info },
    { EVENT_908_RPL_SASLMECHS,         protocol_info },
    
    /* Error handlers */
    { EVENT_ERROR,                     protocol_error },
    { EVENT_400_ERR_UNKNOWNERROR,      protocol_error },
    { EVENT_401_ERR_NOSUCHNICK,        protocol_error },
    { EVENT_402_ERR_NOSUCHSERVER,      protocol_error },
    { EVENT_403_ERR_NOSUCHCHANNEL,     protocol_error },
    { EVENT_404_ERR_CANNOTSENDTOCHAN,  protocol_error },
    { EVENT_405_ERR_TOOMANYCHANNELS,   protocol_error },
    { EVENT_406_ERR_WASNOSUCHNICK,     protocol_error },
    { EVENT_407_ERR_TOOMANYTARGETS,    protocol_error },
    { EVENT_408_ERR_NOSUCHSERVICE,     protocol_error },
    { EVENT_409_ERR_NOORIGIN,          protocol_error },
    { EVENT_411_ERR_NORECIPIENT,       protocol_error },
    { EVENT_412_ERR_NOTEXTTOSEND,      protocol_error },
    { EVENT_413_ERR_NOTOPLEVEL,        protocol_error },
    { EVENT_414_ERR_WILDTOPLEVEL,      protocol_error },
    { EVENT_415_ERR_BADMASK,           protocol_error },
    { EVENT_421_ERR_UNKNOWNCOMMAND,    protocol_error },
    { EVENT_422_ERR_NOMOTD,            protocol_error },
    { EVENT_423_ERR_NOADMININFO,       protocol_error },
    { EVENT_424_ERR_FILEERROR,         protocol_error },
    { EVENT_431_ERR_NONICKNAMEGIVEN,   protocol_error },
    { EVENT_432_ERR_ERRONEUSNICKNAME,  protocol_error },
    { EVENT_433_ERR_NICKNAMEINUSE,     protocol_error },
    { EVENT_436_ERR_NICKCOLLISION,     protocol_error },
    { EVENT_441_ERR_USERNOTINCHANNEL,  protocol_error },
    { EVENT_442_ERR_NOTONCHANNEL,      protocol_error },
    { EVENT_443_ERR_USERONCHANNEL,     protocol_error },
    { EVENT_444_ERR_NOLOGIN,           protocol_error },
    { EVENT_445_ERR_SUMMONDISABLED,    protocol_error },
    { EVENT_446_ERR_USERSDISABLED,     protocol_error },
    { EVENT_451_ERR_NOTREGISTERED,     protocol_error },
    { EVENT_461_ERR_NEEDMOREPARAMS,    protocol_error },
    { EVENT_462_ERR_ALREADYREGISTERED, protocol_error },
    { EVENT_463_ERR_NOPERMFORHOST,     protocol_error },
    { EVENT_464_ERR_PASSWDMISMATCH,    protocol_error },
    { EVENT_465_ERR_YOUREBANNEDCREEP,  protocol_error },
    { EVENT_467_ERR_KEYSET,            protocol_error },
    { EVENT_470_ERR_LINKCHANNEL,       protocol_error },
    { EVENT_471_ERR_CHANNELISFULL,     protocol_error },
    { EVENT_472_ERR_UNKNOWNMODE,       protocol_error },
    { EVENT_473_ERR_INVITEONLYCHAN,    protocol_error },
    { EVENT_474_ERR_BANNEDFROMCHAN,    protocol_error },
    { EVENT_475_ERR_BADCHANNELKEY,     protocol_error },
    { EVENT_476_ERR_BADCHANMASK,       protocol_error },
    { EVENT_477_ERR_NEEDREGGEDNICK,    protocol_error },
    { EVENT_478_ERR_BANLISTFULL,       protocol_error },
    { EVENT_481_ERR_NOPRIVILEGES,      protocol_error },
    { EVENT_482_ERR_CHANOPRIVSNEEDED,  protocol_error },
    { EVENT_483_ERR_CANTKILLSERVER,    protocol_error },
    { EVENT_485_ERR_UNIQOPRIVSNEEDED,  protocol_error },
    { EVENT_491_ERR_NOOPERHOST,        protocol_error },
    { EVENT_501_ERR_UMODEUNKNOWNFLAG,  protocol_error },
    { EVENT_502_ERR_USERSDONTMATCH,    protocol_error },
    { EVENT_524_ERR_HELPNOTFOUND,      protocol_error },
    { EVENT_902_ERR_NICKLOCKED,        protocol_error },
    { EVENT_904_ERR_SASLFAIL,          protocol_error },
    { EVENT_905_ERR_SASLTOOLONG,       protocol_error },
    { EVENT_906_ERR_SASLABORTED,       protocol_error },
    { EVENT_907_ERR_SASLALREADY,       protocol_error },
    
    /* Sentinel */
    { EVENT_NONE,                      NULL } 
};

void handler_dispatch(struct network *network, struct event *event)
{
    for (int i = 0; handler_table[i].handler != NULL; ++i) {
        if (handler_table[i].type == event->type) {
            handler_table[i].handler(network, event);
            return;
        }
    }

    /* If no handler found, display raw message */
    protocol_raw(network, event);
}
